# Necessary for docker
sudo: required
services:
    - docker

language: python
python:
    - 3.3
    - 3.4
    - 3.5
script:
    - python prime_server.py
    - docker build -t willprice/prime-server .
deploy:
    provider: script
    script: upload-to-dockerhub.sh
    on:
        branch: master
