# Necessary for docker
sudo: required
services:
    - docker

language: python
python:
    - 3.3
    - 3.4
    - 3.5
install:
    - pip install -r requirements.txt
script:
    - python prime_tests.py
    - docker build -t willprice/prime-server .
after_success: .travis/deploy.sh
