# Necessary for docker
sudo: required
services:
    - docker

language: python
python:
    - 3.3
    - 3.4
    - 3.5
install:
    - pip install -r requirements.txt
script:
    - python prime_tests.py
    - docker build -t willprice/prime-server .
deploy:
    provider: script
    script: upload-to-dockerhub.sh
    skip_cleanup: true
    on:
        branch: master
        python: 3.5
