prime_server:
    build: .
    expose:
        - 5000
proxy:
    image: jwilder/nginx-proxy
    volumes:
        - '/var/run/docker.sock:/tmp/docker.sock:ro'
    environment:
        VIRTUAL_HOST: "localhost"
        VIRTUAL_PORT: 5000
    ports:
        - '80:80'
        - '443:443'
